### ISSUE TITLE
Issues with `werkzeug` and running without Docker?

### ISSUE THREAD

**Issue by diliprk** [ftadvisory/open-astro-org-web-service#1]
I followed the instructions to create the `.venv` in the project directory. Getting the following error in the docker container:
```
2024-01-25 11:23:09 Traceback (most recent call last):
2024-01-25 11:23:09   File "/open-astro-web-service/app/app.py", line 1, in <module>
2024-01-25 11:23:09     from flask import Flask, request, jsonify
2024-01-25 11:23:09   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
2024-01-25 11:23:09     from .app import Flask as Flask
2024-01-25 11:23:09   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 27, in <module>
2024-01-25 11:23:09     from . import cli
2024-01-25 11:23:09   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 17, in <module>
2024-01-25 11:23:09     from .helpers import get_debug_flag
2024-01-25 11:23:09   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
2024-01-25 11:23:09     from werkzeug.urls import url_quote
2024-01-25 11:23:09 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
2024-01-25 11:23:22 Traceback (most recent call last):
2024-01-25 11:23:22   File "/open-astro-web-service/app/app.py", line 1, in <module>
2024-01-25 11:23:22     from flask import Flask, request, jsonify
2024-01-25 11:23:22   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
2024-01-25 11:23:22     from .app import Flask as Flask
2024-01-25 11:23:22   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 27, in <module>
2024-01-25 11:23:22     from . import cli
2024-01-25 11:23:22   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 17, in <module>
2024-01-25 11:23:22     from .helpers import get_debug_flag
2024-01-25 11:23:22   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
2024-01-25 11:23:22     from werkzeug.urls import url_quote
2024-01-25 11:23:22 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
2024-01-25 11:24:25 Traceback (most recent call last):
2024-01-25 11:24:25   File "/open-astro-web-service/app/app.py", line 1, in <module>
2024-01-25 11:24:25     from flask import Flask, request, jsonify
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
2024-01-25 11:24:25     from .app import Flask as Flask
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 27, in <module>
2024-01-25 11:24:25     from . import cli
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 17, in <module>
2024-01-25 11:24:25     from .helpers import get_debug_flag
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
2024-01-25 11:24:25     from werkzeug.urls import url_quote
2024-01-25 11:24:25 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
2024-01-25 11:24:25 Traceback (most recent call last):
2024-01-25 11:24:25   File "/open-astro-web-service/app/app.py", line 1, in <module>
2024-01-25 11:24:25     from flask import Flask, request, jsonify
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/__init__.py", line 7, in <module>
2024-01-25 11:24:25     from .app import Flask as Flask
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/app.py", line 27, in <module>
2024-01-25 11:24:25     from . import cli
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/cli.py", line 17, in <module>
2024-01-25 11:24:25     from .helpers import get_debug_flag
2024-01-25 11:24:25   File "/usr/local/lib/python3.10/site-packages/flask/helpers.py", line 14, in <module>
2024-01-25 11:24:25     from werkzeug.urls import url_quote
2024-01-25 11:24:25 ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
```
I am using python 3.11 to create the `.venv` ?
Any ideas on how to fix this?

**Comment by ftadvisory** [comment]
@diliprk There seems to have been an issue with the version of Flask.  The repo is updated including some refactoring and is working locally.  Please take a look and revert.

**Comment by diliprk** [comment]
HI @ftadvisory , Thanks for the prompt response and fix.
Yes I was able to get the output in the terminal when `python invoke_service.py` and this `Joanne_Woodward.oac` file got generated in the `data` folder. However there are some issues with your README.MD file:

1. The old port nr.5000 is invalid and the correct localhost port is `http:localhost:5050` as you have updated that in `docker-build.zsh` 
2. There is no `.test` folder and I had to run `python invoke_service.py` and `bash test-webservice-and-cleanup.zsh`
3. Running  `bash test-webservice-and-cleanup.zsh` uninstalls the `openastro`, `pyswisseph` and other packages and thereafter when I try to run `python invoke_service.py` the script stops working because of some module import errors? What is the need or use for running this `test-webservice-and-cleanup.zsh` script?
4. When should the user run `bash app-run.zsh` ? Is this for local testing without using the docker image?
5. How to visualize the generated .oac file on a natal chart , as shown here https://www.linuxlinks.com/openastro/ ?

**Comment by ftadvisory** [comment]
Thanks for the feedback.

The readme has been updated to reflect the changes.

  1.  The shift to 5050 was because port 5000 is used by OSX.
  2.  The test folder was redundant.  All the relevant items were moved to the top level of the project.
  3.  As noted, “test-webservice-and-cleanup.zsh” installs and removes the relevant packages.  The readme is updated with a reminder of how to reinstall the packages should that be needed.
  4.  Yes
  5.  The objective was to wrap the OpenAstro.org code in a web service.  Visualization of the results is out of scope.

Hope this helps.

Good luck.

From: Dilip Rajkumar ***@***.***>
Date: Friday, January 26, 2024 at 8:38 PM
To: ftadvisory/open-astro-org-web-service ***@***.***>
Cc: Daniel Schwartz ***@***.***>, Mention ***@***.***>
Subject: Re: [ftadvisory/open-astro-org-web-service] Issues with `werkzeug` and running without Docker? (Issue #1)

HI @ftadvisory<https://github.com/ftadvisory> , Thanks for the prompt response and fix.
Yes I was able to get the output in the terminal when python invoke_service.py and this Joanne_Woodward.oac file got generated in the data folder. However there are some issues with your README.MD file:

  1.  The old port nr.5000 is invalid and the correct localhost port is http:localhost:5050 as you have updated that in docker-build.zsh
  2.  There is no .test folder and I had to run python invoke_service.py and bash test-webservice-and-cleanup.zsh
  3.  Running bash test-webservice-and-cleanup.zsh uninstalls the openastro, pyswisseph and other packages and thereafter when I try to run python invoke_service.py the script stops working because of some module import errors? What is the need or use for running this test-webservice-and-cleanup.zsh script?
  4.  When should the user run bash app-run.zsh ? Is this for local testing without using the docker image?
  5.  How to visualize the generated .oac file on a natal chart , as shown here https://www.linuxlinks.com/openastro/ ?
